// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BikeMessenger
{
    [Table("CLIENTES")]
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            SERVICIOs = new HashSet<SERVICIO>();
        }

        [Key]
        [Column(TypeName = "nvarchar(512)")]
        public string PENTALPHA { get; set; }
        [Key]
        [Column(TypeName = "nvarchar(12)")]
        public string RUTID { get; set; }
        [Key]
        [Column(TypeName = "nvarchar(5)")]
        public string DIGVER { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string NOMBRE { get; set; }
        [Column(TypeName = "nvarchar(15)")]
        public string USUARIO { get; set; }
        [Column(TypeName = "nvarchar(15)")]
        public string CLAVE { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string ACTIVIDAD1 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string ACTIVIDAD2 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string REPRESENTANTE1 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string REPRESENTANTE2 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string EMAIL { get; set; }
        [Column(TypeName = "nvarchar(15)")]
        public string TELEFONO1 { get; set; }
        [Column(TypeName = "nvarchar(15)")]
        public string TELEFONO2 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string DOMICILIO1 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string DOMICILIO2 { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string NUMERO { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string PISO { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string OFICINA { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string CODIGOPOSTAL { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string CIUDAD { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string COMUNA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string REGION { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string PAIS { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string OBSERVACIONES { get; set; }
        [Column(TypeName = "ntext")]
        public string FOTO { get; set; }

        [ForeignKey(nameof(PENTALPHA))]
        [InverseProperty(nameof(EMPRESA.CLIENTEs))]
        public virtual EMPRESA PENTALPHANavigation { get; set; }
        [InverseProperty(nameof(SERVICIO.CLIENTE))]
        public virtual ICollection<SERVICIO> SERVICIOs { get; set; }
    }
}