// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BikeMessenger
{
    [Table("ESTADOREGION")]
    public partial class ESTADOREGION
    {
        [Key]
        [Column(TypeName = "nvarchar(50)")]
        public string NOMBRE { get; set; }
    }
}