// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BikeMessenger
{
    [Table("PERSONAL")]
    public partial class PERSONAL
    {
        public PERSONAL()
        {
            RECURSOs = new HashSet<RECURSO>();
            SERVICIOs = new HashSet<SERVICIO>();
        }

        [Key]
        [Column(TypeName = "nvarchar(512)")]
        public string PENTALPHA { get; set; }
        [Key]
        [Column(TypeName = "nvarchar(12)")]
        public string RUTID { get; set; }
        [Key]
        [Column(TypeName = "nvarchar(5)")]
        public string DIGVER { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string APELLIDOS { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string NOMBRES { get; set; }
        [Column(TypeName = "nvarchar(14)")]
        public string TELEFONO1 { get; set; }
        [Column(TypeName = "nvarchar(14)")]
        public string TELEFONO2 { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string EMAIL { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string AUTORIZACION { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string CARGO { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string DOMICILIO { get; set; }
        [Column(TypeName = "nvarchar(5)")]
        public string NUMERO { get; set; }
        [Column(TypeName = "nvarchar(5)")]
        public string PISO { get; set; }
        [Column(TypeName = "nvarchar(5)")]
        public string DPTO { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string CODIGOPOSTAL { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string CIUDAD { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string COMUNA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string REGION { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string PAIS { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string OBSERVACIONES { get; set; }
        [Column(TypeName = "ntext")]
        public string FOTO { get; set; }

        [ForeignKey(nameof(PENTALPHA))]
        [InverseProperty(nameof(EMPRESA.PERSONALs))]
        public virtual EMPRESA PENTALPHANavigation { get; set; }
        [InverseProperty(nameof(RECURSO.PERSONAL))]
        public virtual ICollection<RECURSO> RECURSOs { get; set; }
        [InverseProperty(nameof(SERVICIO.PERSONAL))]
        public virtual ICollection<SERVICIO> SERVICIOs { get; set; }
    }
}