// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BikeMessenger
{
    [Table("RECURSOS")]
    public partial class RECURSO
    {
        public RECURSO()
        {
            SERVICIOs = new HashSet<SERVICIO>();
        }

        [Key]
        [Column(TypeName = "nvarchar(512)")]
        public string PENTALPHA { get; set; }
        [Required]
        [Column(TypeName = "nvarchar(12)")]
        public string RUTID { get; set; }
        [Required]
        [Column(TypeName = "nvarchar(5)")]
        public string DIGVER { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string PROPIETARIO { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string TIPO { get; set; }
        [Key]
        [Column(TypeName = "nvarchar(50)")]
        public string PATENTE { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string MARCA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string MODELO { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string VARIANTE { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string ANO { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string COLOR { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string CIUDAD { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string COMUNA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string REGION { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string PAIS { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string OBSERVACIONES { get; set; }
        [Column(TypeName = "ntext")]
        public string FOTO { get; set; }

        [ForeignKey(nameof(PENTALPHA))]
        [InverseProperty(nameof(EMPRESA.RECURSOs))]
        public virtual EMPRESA PENTALPHANavigation { get; set; }
        [ForeignKey("PENTALPHA,RUTID,DIGVER")]
        [InverseProperty("RECURSOs")]
        public virtual PERSONAL PERSONAL { get; set; }
        [InverseProperty(nameof(SERVICIO.RECURSO))]
        public virtual ICollection<SERVICIO> SERVICIOs { get; set; }
    }
}