// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BikeMessenger
{
    [Table("SERVICIOS")]
    public partial class SERVICIO
    {
        [Key]
        [Column(TypeName = "nvarchar(512)")]
        public string PENTALPHA { get; set; }
        [Key]
        [Column(TypeName = "nvarchar(50)")]
        public string NROENVIO { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string GUIADESPACHO { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string FECHA { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string HORA { get; set; }
        [Column(TypeName = "nvarchar(12)")]
        public string CLIENTERUT { get; set; }
        [Column(TypeName = "nvarchar(5)")]
        public string CLIENTEDIGVER { get; set; }
        [Column(TypeName = "nvarchar(12)")]
        public string MENSAJERORUT { get; set; }
        [Column(TypeName = "nvarchar(5)")]
        public string MENSAJERODIGVER { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string RECURSOID { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string ODOMICILIO1 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string ODOMICILIO2 { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string ONUMERO { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string OPISO { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string OOFICINA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string OCIUDAD { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string OCOMUNA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string OESTADO { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string OPAIS { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string OCOORDENADAS { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string DDOMICILIO1 { get; set; }
        [Column(TypeName = "nvarchar(55)")]
        public string DDOMICILIO2 { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string DNUMERO { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string DPISO { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string DOFICINA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string DCIUDAD { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string DCOMUNA { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string DESTADO { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string DPAIS { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public string DCOORDENADAS { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string DESCRIPCION { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string FACTURAS { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string BULTOS { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string COMPRAS { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string CHEQUES { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string SOBRES { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string OTROS { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string OBSERVACIONES { get; set; }
        [Column(TypeName = "nvarchar(64)")]
        public string ENTREGA { get; set; }
        [Column(TypeName = "nvarchar(64)")]
        public string RECEPCION { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string TESPERA { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string FECHAENTREGA { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string HORAENTREGA { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string DISTANCIA { get; set; }
        [Column(TypeName = "nvarchar(25)")]
        public string PROGRAMADO { get; set; }

        [ForeignKey("PENTALPHA,CLIENTERUT,CLIENTEDIGVER")]
        [InverseProperty("SERVICIOs")]
        public virtual CLIENTE CLIENTE { get; set; }
        [ForeignKey(nameof(PENTALPHA))]
        [InverseProperty(nameof(EMPRESA.SERVICIOs))]
        public virtual EMPRESA PENTALPHANavigation { get; set; }
        [ForeignKey("PENTALPHA,MENSAJERORUT,MENSAJERODIGVER")]
        [InverseProperty("SERVICIOs")]
        public virtual PERSONAL PERSONAL { get; set; }
        [ForeignKey("PENTALPHA,RECURSOID")]
        [InverseProperty("SERVICIOs")]
        public virtual RECURSO RECURSO { get; set; }
    }
}