BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ESTADOREGION" (
	"CODPAIS"	INTEGER NOT NULL,
	"CODREGION"	INTEGER NOT NULL,
	"REGION"	TEXT NOT NULL,
	PRIMARY KEY("CODPAIS","CODREGION")
);
CREATE TABLE IF NOT EXISTS "COMUNA" (
	"CODPAIS"	INTEGER NOT NULL,
	"CODREGION"	INTEGER NOT NULL,
	"CODCOMU"	INTEGER NOT NULL,
	"COMUNA"	TEXT NOT NULL,
	PRIMARY KEY("CODPAIS","CODREGION","CODCOMU")
);
CREATE TABLE IF NOT EXISTS "EMPRESA" (
	"RUTID"	TEXT NOT NULL,
	"DIGVER"	TEXT NOT NULL DEFAULT 0,
	"LOGO"	BLOB,
	"NOMBRE"	TEXT,
	"ACTIVIDAD"	TEXT,
	"REPRESENTANTES"	TEXT,
	"DOMICILIO1"	TEXT,
	"DOMICILIO2"	TEXT,
	"NUMERO"	TEXT,
	"PISO"	TEXT,
	"OFICINA"	TEXT,
	"CIUDAD"	TEXT,
	"COMUNA"	TEXT,
	"ESTADOREGION"	TEXT,
	"CODIGOPOSTAL"	TEXT,
	"PAIS"	TEXT,
	PRIMARY KEY("RUTID","DIGVER")
);
CREATE TABLE IF NOT EXISTS "CIUDAD" (
	"PAIS"	INTEGER NOT NULL,
	"REGION"	INTEGER NOT NULL,
	"COMUNA"	INTEGER NOT NULL,
	"CODCIUDAD"	INTEGER NOT NULL,
	"CIUDAD"	TEXT NOT NULL,
	PRIMARY KEY("PAIS","REGION","COMUNA","CODCIUDAD")
);
CREATE TABLE IF NOT EXISTS "PAIS" (
	"CODPAIS"	INTEGER NOT NULL,
	"PAIS"	TEXT NOT NULL,
	PRIMARY KEY("CODPAIS")
);
INSERT INTO "EMPRESA" ("RUTID","DIGVER","LOGO","NOMBRE","ACTIVIDAD","REPRESENTANTES","DOMICILIO1","DOMICILIO2","NUMERO","PISO","OFICINA","CIUDAD","COMUNA","ESTADOREGION","CODIGOPOSTAL","PAIS") VALUES ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','Chile');
INSERT INTO "PAIS" ("CODPAIS","PAIS") VALUES (10,'Argentina'),
 (20,'Bolivia'),
 (30,'Brasil'),
 (40,'Chile'),
 (50,'Colombia'),
 (60,'Costa Rica'),
 (70,'Cuba'),
 (80,'Ecuador'),
 (90,'El Salvador'),
 (100,'Guayana Francesa'),
 (110,'Granada'),
 (120,'Guatemala'),
 (130,'Guayana'),
 (140,'Haiti'),
 (150,'Honduras'),
 (160,'Jamaica'),
 (170,'Mexico'),
 (180,'Nicaragua'),
 (190,'Paraguay'),
 (200,'Panama'),
 (210,'Peru'),
 (220,'Puerto Rico'),
 (230,'Republica Dominicana'),
 (240,'Surinam'),
 (250,'Uruguay'),
 (260,'Venezuela');
COMMIT;
