USE [bikemessenger]
GO

/****** Object:  User [BikeMessenger]    Script Date: 6/19/2021 12:30:13 ******/
DROP USER [BikeMessenger]
GO

/****** Object:  User [BikeMessenger]    Script Date: 6/19/2021 12:30:13 ******/
CREATE USER [BikeMessenger] FOR LOGIN [bikemessenger] WITH DEFAULT_SCHEMA=[dbo]
GO


USE [master]
GO

/****** Object:  Database [bikemessenger]    Script Date: 6/19/2021 12:29:10 ******/
DROP DATABASE [bikemessenger]
GO

/****** Object:  Database [bikemessenger]    Script Date: 6/19/2021 12:29:10 ******/
CREATE DATABASE [bikemessenger]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bikemessenger', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\bikemessenger.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bikemessenger_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\bikemessenger_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bikemessenger].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bikemessenger] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bikemessenger] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bikemessenger] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bikemessenger] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bikemessenger] SET ARITHABORT OFF 
GO

ALTER DATABASE [bikemessenger] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bikemessenger] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bikemessenger] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bikemessenger] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bikemessenger] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bikemessenger] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bikemessenger] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bikemessenger] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bikemessenger] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bikemessenger] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bikemessenger] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bikemessenger] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bikemessenger] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bikemessenger] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bikemessenger] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bikemessenger] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bikemessenger] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bikemessenger] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bikemessenger] SET  MULTI_USER 
GO

ALTER DATABASE [bikemessenger] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bikemessenger] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bikemessenger] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bikemessenger] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bikemessenger] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bikemessenger] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [bikemessenger] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bikemessenger] SET  READ_WRITE 
GO



USE [bikemessenger]
GO

/****** Object:  Table [dbo].[EMPRESA]    Script Date: 6/19/2021 14:07:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPRESA](
	[PENTALPHA] [varchar](512) NOT NULL,
	[RUTID] [varchar](12) NOT NULL,
	[DIGVER] [varchar](5) NOT NULL,
	[NOMBRE] [varchar](55) NULL,
	[USUARIO] [varchar](15) NOT NULL,
	[CLAVE] [varchar](15) NOT NULL,
	[ACTIVIDAD1] [varchar](55) NULL,
	[ACTIVIDAD2] [varchar](55) NULL,
	[REPRESENTANTE1] [varchar](55) NULL,
	[REPRESENTANTE2] [varchar](55) NULL,
	[REPRESENTANTE3] [varchar](55) NULL,
	[DOMICILIO1] [varchar](55) NULL,
	[DOMICILIO2] [varchar](55) NULL,
	[NUMERO] [varchar](10) NULL,
	[PISO] [varchar](10) NULL,
	[OFICINA] [varchar](10) NULL,
	[CIUDAD] [varchar](50) NULL,
	[COMUNA] [varchar](50) NULL,
	[ESTADOREGION] [varchar](50) NULL,
	[CODIGOPOSTAL] [varchar](25) NULL,
	[PAIS] [varchar](50) NULL,
	[TELEFONO1] [varchar](15) NULL,
	[TELEFONO2] [varchar](15) NULL,
	[TELEFONO3] [varchar](15) NULL,
	[OBSERVACIONES] [varchar](250) NULL,
	[LOGO] [varchar](max) NULL,
 CONSTRAINT [PK_EMPRESA] PRIMARY KEY CLUSTERED 
(
	[PENTALPHA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[CIUDAD]    Script Date: 6/19/2021 14:08:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CIUDAD](
	[NOMBRE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CIUDAD] PRIMARY KEY CLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[CLIENTES]    Script Date: 6/19/2021 14:08:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTES](
	[PENTALPHA] [varchar](512) NOT NULL,
	[RUTID] [varchar](12) NOT NULL,
	[DIGVER] [varchar](5) NOT NULL,
	[NOMBRE] [varchar](55) NULL,
	[USUARIO] [varchar](15) NULL,
	[CLAVE] [varchar](15) NULL,
	[ACTIVIDAD1] [varchar](55) NULL,
	[ACTIVIDAD2] [varchar](55) NULL,
	[REPRESENTANTE1] [varchar](55) NULL,
	[REPRESENTANTE2] [varchar](55) NULL,
	[EMAIL] [varchar](55) NULL,
	[TELEFONO1] [varchar](15) NULL,
	[TELEFONO2] [varchar](15) NULL,
	[DOMICILIO1] [varchar](55) NULL,
	[DOMICILIO2] [varchar](55) NULL,
	[NUMERO] [varchar](10) NULL,
	[PISO] [varchar](10) NULL,
	[OFICINA] [varchar](10) NULL,
	[CODIGOPOSTAL] [varchar](25) NULL,
	[CIUDAD] [varchar](50) NULL,
	[COMUNA] [varchar](50) NULL,
	[REGION] [varchar](50) NULL,
	[PAIS] [varchar](50) NULL,
	[OBSERVACIONES] [varchar](250) NULL,
	[FOTO] [varchar](max) NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[PENTALPHA] ASC,
	[RUTID] ASC,
	[DIGVER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLIENTES]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTES_EMPRESA] FOREIGN KEY([PENTALPHA])
REFERENCES [dbo].[EMPRESA] ([PENTALPHA])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CLIENTES] CHECK CONSTRAINT [FK_CLIENTES_EMPRESA]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[COMUNA]    Script Date: 6/19/2021 14:08:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMUNA](
	[NOMBRE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_COMUNA] PRIMARY KEY CLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[ESTADOREGION]    Script Date: 6/19/2021 14:09:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESTADOREGION](
	[NOMBRE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ESTADOREGION] PRIMARY KEY CLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[PAIS]    Script Date: 6/19/2021 14:09:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAIS](
	[NOMBRE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PAIS] PRIMARY KEY CLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[PERSONAL]    Script Date: 6/19/2021 14:09:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSONAL](
	[PENTALPHA] [varchar](512) NOT NULL,
	[RUTID] [varchar](12) NOT NULL,
	[DIGVER] [varchar](5) NOT NULL,
	[APELLIDOS] [varchar](55) NULL,
	[NOMBRES] [varchar](55) NULL,
	[TELEFONO1] [varchar](14) NULL,
	[TELEFONO2] [varchar](14) NULL,
	[EMAIL] [varchar](25) NULL,
	[AUTORIZACION] [varchar](25) NULL,
	[CARGO] [varchar](55) NULL,
	[DOMICILIO] [varchar](55) NULL,
	[NUMERO] [varchar](5) NULL,
	[PISO] [varchar](5) NULL,
	[DPTO] [varchar](5) NULL,
	[CODIGOPOSTAL] [varchar](25) NULL,
	[CIUDAD] [varchar](50) NULL,
	[COMUNA] [varchar](50) NULL,
	[REGION] [varchar](50) NULL,
	[PAIS] [varchar](50) NULL,
	[OBSERVACIONES] [varchar](250) NULL,
	[FOTO] [varchar](max) NULL,
 CONSTRAINT [PK_PERSONAL] PRIMARY KEY CLUSTERED 
(
	[PENTALPHA] ASC,
	[RUTID] ASC,
	[DIGVER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PERSONAL]  WITH CHECK ADD  CONSTRAINT [FK_PERSONAL_EMPRESA] FOREIGN KEY([PENTALPHA])
REFERENCES [dbo].[EMPRESA] ([PENTALPHA])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PERSONAL] CHECK CONSTRAINT [FK_PERSONAL_EMPRESA]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[RECURSOS]    Script Date: 6/19/2021 14:09:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RECURSOS](
	[PENTALPHA] [varchar](512) NOT NULL,
	[RUTID] [varchar](12) NOT NULL,
	[DIGVER] [varchar](5) NOT NULL,
	[PROPIETARIO] [varchar](50) NULL,
	[TIPO] [varchar](50) NULL,
	[PATENTE] [varchar](50) NOT NULL,
	[MARCA] [varchar](50) NULL,
	[MODELO] [varchar](50) NULL,
	[VARIANTE] [varchar](50) NULL,
	[ANO] [varchar](50) NULL,
	[COLOR] [varchar](50) NULL,
	[CIUDAD] [varchar](50) NULL,
	[COMUNA] [varchar](50) NULL,
	[REGION] [varchar](50) NULL,
	[PAIS] [varchar](50) NULL,
	[OBSERVACIONES] [varchar](250) NULL,
	[FOTO] [varchar](max) NULL,
 CONSTRAINT [PK_RECURSOS] PRIMARY KEY CLUSTERED 
(
	[PENTALPHA] ASC,
	[PATENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RECURSOS]  WITH CHECK ADD  CONSTRAINT [FK_RECURSOS_EMPRESA] FOREIGN KEY([PENTALPHA])
REFERENCES [dbo].[EMPRESA] ([PENTALPHA])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[RECURSOS] CHECK CONSTRAINT [FK_RECURSOS_EMPRESA]
GO

ALTER TABLE [dbo].[RECURSOS]  WITH CHECK ADD  CONSTRAINT [FK_RECURSOS_PROPIETARIO] FOREIGN KEY([PENTALPHA], [RUTID], [DIGVER])
REFERENCES [dbo].[PERSONAL] ([PENTALPHA], [RUTID], [DIGVER])
GO

ALTER TABLE [dbo].[RECURSOS] CHECK CONSTRAINT [FK_RECURSOS_PROPIETARIO]
GO

USE [bikemessenger]
GO

/****** Object:  Table [dbo].[SERVICIOS]    Script Date: 6/19/2021 14:09:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SERVICIOS](
	[PENTALPHA] [varchar](512) NOT NULL,
	[NROENVIO] [varchar](50) NOT NULL,
	[GUIADESPACHO] [varchar](50) NULL,
	[FECHA] [varchar](25) NULL,
	[HORA] [varchar](25) NULL,
	[CLIENTERUT] [varchar](12) NULL,
	[CLIENTEDIGVER] [varchar](5) NULL,
	[MENSAJERORUT] [varchar](12) NULL,
	[MENSAJERODIGVER] [varchar](5) NULL,
	[RECURSOID] [varchar](50) NULL,
	[ODOMICILIO1] [varchar](55) NULL,
	[ODOMICILIO2] [varchar](55) NULL,
	[ONUMERO] [varchar](10) NULL,
	[OPISO] [varchar](10) NULL,
	[OOFICINA] [varchar](10) NULL,
	[OCIUDAD] [varchar](50) NULL,
	[OCOMUNA] [varchar](50) NULL,
	[OESTADO] [varchar](50) NULL,
	[OPAIS] [varchar](50) NULL,
	[OCOORDENADAS] [varchar](50) NULL,
	[DDOMICILIO1] [varchar](55) NULL,
	[DDOMICILIO2] [varchar](55) NULL,
	[DNUMERO] [varchar](10) NULL,
	[DPISO] [varchar](10) NULL,
	[DOFICINA] [varchar](10) NULL,
	[DCIUDAD] [varchar](50) NULL,
	[DCOMUNA] [varchar](50) NULL,
	[DESTADO] [varchar](50) NULL,
	[DPAIS] [varchar](50) NULL,
	[DCOORDENADAS] [varchar](50) NULL,
	[DESCRIPCION] [varchar](250) NULL,
	[FACTURAS] [varchar](25) NULL,
	[BULTOS] [varchar](25) NULL,
	[COMPRAS] [varchar](25) NULL,
	[CHEQUES] [varchar](25) NULL,
	[SOBRES] [varchar](25) NULL,
	[OTROS] [varchar](25) NULL,
	[OBSERVACIONES] [varchar](250) NULL,
	[ENTREGA] [varchar](64) NULL,
	[RECEPCION] [varchar](64) NULL,
	[TESPERA] [varchar](25) NULL,
	[FECHAENTREGA] [varchar](25) NULL,
	[HORAENTREGA] [varchar](25) NULL,
	[DISTANCIA] [varchar](25) NULL,
	[PROGRAMADO] [varchar](25) NULL,
 CONSTRAINT [PK_SERVICIOS] PRIMARY KEY CLUSTERED 
(
	[PENTALPHA] ASC,
	[NROENVIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SERVICIOS]  WITH CHECK ADD  CONSTRAINT [FK_SERVICIOS_CLIENTES] FOREIGN KEY([PENTALPHA], [CLIENTERUT], [CLIENTEDIGVER])
REFERENCES [dbo].[CLIENTES] ([PENTALPHA], [RUTID], [DIGVER])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SERVICIOS] CHECK CONSTRAINT [FK_SERVICIOS_CLIENTES]
GO

ALTER TABLE [dbo].[SERVICIOS]  WITH CHECK ADD  CONSTRAINT [FK_SERVICIOS_EMPRESA] FOREIGN KEY([PENTALPHA])
REFERENCES [dbo].[EMPRESA] ([PENTALPHA])
GO

ALTER TABLE [dbo].[SERVICIOS] CHECK CONSTRAINT [FK_SERVICIOS_EMPRESA]
GO

ALTER TABLE [dbo].[SERVICIOS]  WITH CHECK ADD  CONSTRAINT [FK_SERVICIOS_MENSAJERO] FOREIGN KEY([PENTALPHA], [MENSAJERORUT], [MENSAJERODIGVER])
REFERENCES [dbo].[PERSONAL] ([PENTALPHA], [RUTID], [DIGVER])
GO

ALTER TABLE [dbo].[SERVICIOS] CHECK CONSTRAINT [FK_SERVICIOS_MENSAJERO]
GO

ALTER TABLE [dbo].[SERVICIOS]  WITH CHECK ADD  CONSTRAINT [FK_SERVICIOS_RECURSOS] FOREIGN KEY([PENTALPHA], [RECURSOID])
REFERENCES [dbo].[RECURSOS] ([PENTALPHA], [PATENTE])
GO

ALTER TABLE [dbo].[SERVICIOS] CHECK CONSTRAINT [FK_SERVICIOS_RECURSOS]
GO


